// lib/countries.ts
export const arabicCountries = [
  { value: "الأردن", label: "الأردن" },
  { value: "السعودية", label: "السعودية" },
  { value: "مصر", label: "مصر" },
  { value: "فلسطين", label: "فلسطين" },
  { value: "سوريا", label: "سوريا" },
  { value: "العراق", label: "العراق" },
  { value: "الإمارات", label: "الإمارات" },
  { value: "قطر", label: "قطر" },
  { value: "البحرين", label: "البحرين" },
  { value: "الكويت", label: "الكويت" },
  { value: "ليبيا", label: "ليبيا" },
  { value: "الجزائر", label: "الجزائر" },
  { value: "تونس", label: "تونس" },
  { value: "المغرب", label: "المغرب" },
  { value: "السودان", label: "السودان" },
  { value: "لبنان", label: "لبنان" },
  { value: "عُمان", label: "عُمان" },
  { value: "اليمن", label: "اليمن" },
  { value: "تركيا", label: "تركيا" },
  { value: "فرنسا", label: "فرنسا" },
  { value: "ألمانيا", label: "ألمانيا" },
  { value: "الولايات المتحدة", label: "الولايات المتحدة" },
  { value: "كندا", label: "كندا" },
  { value: "بريطانيا", label: "بريطانيا" },
  { value: "أستراليا", label: "أستراليا" },
  // ... أضف دول أخرى حسب حاجتك
]
